apiVersion: v1
appVersion: 6.8.18-oss
description: Official Elastic helm chart for Elasticsearch
home: https://github.com/elastic/helm-charts
icon: https://helm.elastic.co/icons/elasticsearch.png
maintainers:
- email: helm-charts@elastic.co
  name: Elastic
name: elasticsearch
sources:
- https://github.com/elastic/elasticsearch
version: 6.8.18-oss




docker run --name kibana --net elastic -p 5601:5601 -e "ELASTICSEARCH_HOSTS=http://10.10.7.224:32110" docker.elastic.co/kibana/kibana-oss:6.8.18